---
# defaults file for oneview_enclosure_group
oneview_enclosure_group_config: "{{ role_path }}/files/oneview_config.json"
oneview_enclosure_group_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
