---
# ---
# defaults file for oneview_sas_interconnect
oneview_sas_interconnect_config: "{{ role_path }}/files/oneview_config.json"
oneview_sas_interconnect_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
