---
# defaults file for oneview_storage_volume_template
oneview_storage_volume_template_config: "{{ role_path }}/files/oneview_config.json"
oneview_storage_volume_template_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
