---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_storage_volume_template_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_storage_volume_template_facts_session

- name: Get currentVersion from URL
  oneview_version_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
  delegate_to: localhost
  when: oneview_storage_volume_template_facts_config_file.api_version == ""
  register: oneview_storage_volume_template_facts_version

- name: Print currentVersion if an apiVersion is not specified in config file
  ansible.builtin.set_fact:
    oneview_storage_volume_template_facts_current_version: "{{ oneview_storage_volume_template_facts_version.ansible_facts.version.currentVersion | int }}"
  when: oneview_storage_volume_template_facts_config_file.api_version == ""

- name: Print currentVersion if an apiVersion is specified in config file
  ansible.builtin.set_fact:
    oneview_storage_volume_template_facts_current_version: oneview_storage_volume_template_facts_config_file.api_version | string
  when: oneview_storage_volume_template_facts_config_file.api_version != ""

- name: Gather facts about all Storage Volume Templates
  oneview_storage_volume_template_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: storage_volume_templates

- name: Gather paginated, filtered and sorted facts about Storage Volume Templates
  oneview_storage_volume_template_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
    params:
      start: 0
      count: 3
      sort: name:descending
      filter: status='OK'

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: storage_volume_templates

- name: Gather facts about a Storage Volume Template by name
  oneview_storage_volume_template_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
    name: "{{ oneview_storage_volume_template_facts_contents.storage_volume.volume_template_name }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: storage_volume_templates

- name: Gather facts about all Fibre Channel Networks
  oneview_fc_network_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: fc_networks

# Only available after API500
- name: Gather facts about the reachable Storage Volume Templates
  oneview_storage_volume_template_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
    options:
      - reachableVolumeTemplates
    params:
      networks: "{{ fc_networks[0]['uri'] }}"
  delegate_to: localhost
  when: currentVersion >= '500' and fc_networks[0]['uri'] is defined

- name: Gather facts about Storage Systems compatible to the SVT
  oneview_storage_volume_template_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
    name: "{{ oneview_storage_volume_template_facts_contents.storage_volume.volume_template_name }}"
    options:
      - compatibleSystems
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: compatible_systems

# Only available prior to API500
- name: Gather facts about the connectable Storage Volume Templates
  oneview_storage_volume_template_facts:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
    name: "{{ oneview_storage_volume_template_facts_contents.storage_volume.volume_template_name }}"
    options:
      - connectableVolumeTemplates
  delegate_to: localhost
  when: currentVersion <= '500'

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: storage_volume_templates
- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: connectable_volume_templates

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_storage_volume_template_facts_config }}"
    sessionID: "{{ oneview_storage_volume_template_facts_session.ansible_facts.session }}"
  delegate_to: localhost
