---
# defaults file for oneview_interconnect
oneview_interconnect_config: "{{ role_path }}/files/oneview_config.json"
oneview_interconnect_config_file: "{{ lookup('file', oneview_interconnect_config) }}"
oneview_interconnect_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
