---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_sas_logical_interconnect_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_sas_logical_interconnect_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_sas_logical_interconnect_facts_session

- name: Gather facts about all SAS Logical Interconnects
  oneview_sas_logical_interconnect_facts:
    config: "{{ oneview_sas_logical_interconnect_facts_config }}"
    sessionID: "{{ oneview_sas_logical_interconnect_facts_session.ansible_facts.session }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: sas_logical_interconnects

- name: Run ansible.builtin.set_fact
  ansible.builtin.set_fact:
    oneview_sas_logical_interconnect_facts_sas_logical_interconnect_name: "{{ sas_logical_interconnects[0]['name'] }}"
- name: Run ansible.builtin.set_fact
  ansible.builtin.set_fact:
    oneview_sas_logical_interconnect_facts_sas_logical_interconnect_uri: "{{ sas_logical_interconnects[0]['uri'] }}"

- name: Gather paginated, filtered and sorted facts about SAS Logical Interconnects
  oneview_sas_logical_interconnect_facts:
    config: "{{ oneview_sas_logical_interconnect_facts_config }}"
    sessionID: "{{ oneview_sas_logical_interconnect_facts_session.ansible_facts.session }}"
    params:
      start: 0
      count: 3
      sort: name:descending
      filter: status=OK

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: sas_logical_interconnects

- name: Gather facts about an SAS Logical interconnect by name
  oneview_sas_logical_interconnect_facts:
    config: "{{ oneview_sas_logical_interconnect_facts_config }}"
    sessionID: "{{ oneview_sas_logical_interconnect_facts_session.ansible_facts.session }}"
    name: "{{ oneview_sas_logical_interconnect_facts_sas_logical_interconnect_name }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: sas_logical_interconnects

- name: Gather facts about an SAS Logical interconnect by uri
  oneview_sas_logical_interconnect_facts:
    config: "{{ oneview_sas_logical_interconnect_facts_config }}"
    sessionID: "{{ oneview_sas_logical_interconnect_facts_session.ansible_facts.session }}"
    uri: "{{ oneview_sas_logical_interconnect_facts_sas_logical_interconnect_uri }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: sas_logical_interconnects

- name: Gather baseline firmware facts about a SAS Logical interconnect by name
  oneview_sas_logical_interconnect_facts:
    config: "{{ oneview_sas_logical_interconnect_facts_config }}"
    sessionID: "{{ oneview_sas_logical_interconnect_facts_session.ansible_facts.session }}"
    name: "{{ oneview_sas_logical_interconnect_facts_sas_logical_interconnect_name }}"
    options:
      - firmware_facts
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: firmware_facts

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_sas_logical_interconnect_facts_config }}"
    sessionID: "{{ oneview_sas_logical_interconnect_facts_session.ansible_facts.session }}"
  delegate_to: localhost
