#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


class ModuleDocFragment(object):
    # OneView doc fragment
    DOCUMENTATION = '''
options:
    config:
      description:
        - Path to a .json configuration file containing the OneView client configuration.
          The configuration file is optional. If the file path is not provided, the configuration will be loaded from
          environment variables.
      required: false
      type: path

notes:
    - "A sample configuration file for the config parameter can be found at:
       U(https://github.com/HewlettPackard/oneview-ansible/blob/master/examples/oneview_config-rename.json)"
    - "Check how to use environment variables for configuration at:
       U(https://github.com/HewlettPackard/oneview-ansible#environment-variables)"
    - "Additional Playbooks for the HPE OneView Ansible modules can be found at:
       U(https://github.com/HewlettPackard/oneview-ansible/tree/master/examples)"
    '''

    VALIDATEETAG = '''
options:
    validate_etag:
        description:
            - When the ETag Validation is enabled, the request will be conditionally processed only if the current ETag
                for the resource matches the ETag provided in the data.
        default: true
        choices: []
        type: bool
'''

    FACTSPARAMS = '''
options:
    params:
        description:
        - List of params to delimit, filter and sort the list of resources.
        - "params allowed:
            C(start): The first item to return, using 0-based indexing.
            C(count): The number of resources to return.
            C(filter): A general filter/query string to narrow the list of items returned.
            C(sort): The sort order of the returned data set."
        required: false
        type: dict
'''

    PARAMS = '''
options:
    api_version:
        description:
            - List with the api_version.
        required: false
        type: int
    hostname:
        description:
            - List with the hostname.
        required: false
        type: str
    image_streamer_hostname:
        description:
            - List with the image_streamer_hostname.
        required: false
        type: str
    password:
        description:
            - List with the password.
        required: false
        type: str
    auth_login_domain:
        description:
            - List with the auth_login_domain.
        required: false
        type: str
    username:
        description:
            - List with the username.
        required: false
        type: str
'''
