---
# defaults file for oneview_network_set
oneview_network_set_config: "{{ role_path }}/files/oneview_config.json"
oneview_network_set_config_file: "{{ lookup('file', oneview_network_set_config) }}"
oneview_network_set_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
