---
# defaults file for oneview_firmware_bundle
oneview_firmware_bundle_config: "{{ role_path }}/files/oneview_config.json"
oneview_firmware_bundle_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
