---
# ---
# defaults file for oneview_sas_logical_jbod
oneview_sas_logical_jbod_config: "{{ role_path }}/files/oneview_config.json"
oneview_sas_logical_jbod_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
