---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_hypervisor_manager_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_hypervisor_manager_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_hypervisor_manager_facts_session

- name: Gather facts about all Hypervisor Managers
  oneview_hypervisor_manager_facts:
    config: "{{ oneview_hypervisor_manager_facts_config }}"
    sessionID: "{{ oneview_hypervisor_manager_facts_session.ansible_facts.session }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: hypervisor_managers

- name: Gather paginated, filtered and sorted facts about Hypervisor Managers
  oneview_hypervisor_manager_facts:
    config: "{{ oneview_hypervisor_manager_facts_config }}"
    sessionID: "{{ oneview_hypervisor_manager_facts_session.ansible_facts.session }}"
    params:
      start: 0
      count: 3
      sort: name:descending
      filter: hypervisorType=Vmware
- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: hypervisor_managers

- name: Gather facts about a Hypervisor Manager by name
  oneview_hypervisor_manager_facts:
    config: "{{ oneview_hypervisor_manager_facts_config }}"
    sessionID: "{{ oneview_hypervisor_manager_facts_session.ansible_facts.session }}"
    name: "{{ oneview_hypervisor_manager_facts_hypervisor_manager_name }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: hypervisor_managers

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_hypervisor_manager_facts_config }}"
    sessionID: "{{ oneview_hypervisor_manager_facts_session.ansible_facts.session }}"
  delegate_to: localhost
