---
# defaults file for oneview_server_profile_template
oneview_server_profile_template_config: "{{ role_path }}/files/oneview_config.json"
oneview_server_profile_template_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
