---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_label_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_label_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_label_session

- name: Gather facts about all Enclosures
  oneview_enclosure_facts:
    config: "{{ oneview_label_config }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: enclosures[0]['uri']

- name: Create Labels for enclosure resource
  oneview_label:
    config: "{{ oneview_label_config }}"
    sessionID: "{{ oneview_label_session.ansible_facts.session }}"
    state: present
    data:
      resourceUri: "{{ enclosures[0]['uri'] }}"
      labels:
        - name: "{{ oneview_label_contents.labels.label_name_1 }}"
        - name: "{{ oneview_label_contents.labels.label_name_2 }}"
  delegate_to: localhost

- name: Update label of given resource for enclosure resource
  oneview_label:
    config: "{{ oneview_label_config }}"
    sessionID: "{{ oneview_label_session.ansible_facts.session }}"
    state: present
    data:
      resourceUri: "{{ enclosures[0]['uri'] }}"
      labels:
        - name: "{{ oneview_label_contents.labels.label_rename_1 }}"
          uri: "{{ labels['labels'][0]['uri'] }}"
        - name: "{{ oneview_label_contents.labels.label_rename_2 }}"
          uri:
        - name: "{{ oneview_label_contents.labels.label_name_3 }}"
          uri:
  delegate_to: localhost

- name: Delete Labels for enclosure resource
  oneview_label:
    config: "{{ oneview_label_config }}"
    sessionID: "{{ oneview_label_session.ansible_facts.session }}"
    state: absent
    data:
      resourceUri: "{{ enclosures[0]['uri'] }}"
  delegate_to: localhost

- name: Create Labels for enclosure resource
  oneview_label:
    config: "{{ oneview_label_config }}"
    state: present
    data:
      resourceUri: "{{ enclosures[0]['uri'] }}"
      labels:
        - name: "{{ oneview_label_contents.labels.label_name_1 }}"
        - name: "{{ oneview_label_contents.labels.label_name_2 }}"
  delegate_to: localhost

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_label_config }}"
    sessionID: "{{ oneview_label_session.ansible_facts.session }}"
  delegate_to: localhost
