---
# defaults file for oneview_appliance_network_interfaces
oneview_appliance_network_interfaces_config: "{{ role_path }}/files/oneview_config.json"
oneview_appliance_network_interfaces_mac_address: <mac_address>
oneview_appliance_network_interfaces_hostname: ci-00505698f13e.com
oneview_appliance_network_interfaces_app1_ipv4_address: <ip1>
oneview_appliance_network_interfaces_app2_ipv4_address: <ip2>
oneview_appliance_network_interfaces_ipv4_address: <ip_address>
oneview_appliance_network_interfaces_ipv4_subnet: <subnet_id>
oneview_appliance_network_interfaces_gateway: <gateway>
oneview_appliance_network_interfaces_dns_server_1: <dns1>
oneview_appliance_network_interfaces_dns_server_2: <dns2>
oneview_appliance_network_interfaces_dns_server_3: <dns3>
