---
# defaults file for oneview_appliance_device_snmp_v1_trap_destination
oneview_appliance_device_snmp_v1_trap_destination_config: "{{ role_path }}/files/oneview_config.json"
oneview_appliance_device_snmp_v1_trap_destination_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
