---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_scope_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_scope_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_scope_facts_session

- name: Gather facts about all Scopes
  oneview_scope_facts:
    config: "{{ oneview_scope_facts_config }}"
    sessionID: "{{ oneview_scope_facts_session.ansible_facts.session }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: scopes

- name: Gather paginated, filtered and sorted facts about Scopes
  oneview_scope_facts:
    config: "{{ oneview_scope_facts_config }}"
    sessionID: "{{ oneview_scope_facts_session.ansible_facts.session }}"
    params:
      start: 0
      count: 3
      sort: name:ascending
      query: name eq 'SampleScope'
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: scopes

- name: Gather facts about a Scope by name
  oneview_scope_facts:
    config: "{{ oneview_scope_facts_config }}"
    sessionID: "{{ oneview_scope_facts_session.ansible_facts.session }}"
    name: "{{ oneview_scope_facts_contents.scope.scope_name }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: scopes

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_scope_facts_config }}"
    sessionID: "{{ oneview_scope_facts_session.ansible_facts.session }}"
  delegate_to: localhost
