---
# defaults file for oneview_network_set_facts
oneview_network_set_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_network_set_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
