---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_firmware_driver_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_firmware_driver_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_firmware_driver_facts_session

- name: Gather facts about all Firmware Drivers
  oneview_firmware_driver_facts:
    config: "{{ oneview_firmware_driver_facts_config }}"
    sessionID: "{{ oneview_firmware_driver_facts_session.ansible_facts.session }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: firmware_drivers

- name: Gather paginated, filtered and sorted facts about Firmware Drivers
  oneview_firmware_driver_facts:
    config: "{{ oneview_firmware_driver_facts_config }}"
    sessionID: "{{ oneview_firmware_driver_facts_session.ansible_facts.session }}"
    params:
      start: 0
      count: 3
      sort: name:descending
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: firmware_drivers

- name: Gather facts about a Firmware Driver by name
  oneview_firmware_driver_facts:
    config: "{{ oneview_firmware_driver_facts_config }}"
    sessionID: "{{ oneview_firmware_driver_facts_session.ansible_facts.session }}"
    name: "{{ oneview_firmware_driver_facts_contents.firmware_driver.baseline_firmware_name }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: firmware_drivers

- name: Gather facts about a Firmware Driver by name and version
  oneview_firmware_driver_facts:
    config: "{{ oneview_firmware_driver_facts_config }}"
    sessionID: "{{ oneview_firmware_driver_facts_session.ansible_facts.session }}"
    name: "{{ oneview_firmware_driver_facts_contents.firmware_driver.baseline_firmware_name }}"
    version: "{{ oneview_firmware_driver_facts_contents.firmware_driver.version }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: firmware_drivers

- name: Gather facts about Firmware Driver with options
  oneview_firmware_driver_facts:
    config: "{{ oneview_firmware_driver_facts_config }}"
    sessionID: "{{ oneview_firmware_driver_facts_session.ansible_facts.session }}"
    options:
      - schema
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: schema

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_firmware_driver_facts_config }}"
    sessionID: "{{ oneview_firmware_driver_facts_session.ansible_facts.session }}"
  delegate_to: localhost
