---
# defaults file for oneview_hypervisor_manager

oneview_hypervisor_manager_config: "{{ role_path }}/files/oneview_config.json"
oneview_hypervisor_manager_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
oneview_hypervisor_manager_config_file: "{{ lookup('file', oneview_hypervisor_manager_config) }}"
