---
# defaults file for oneview_firmware_driver
oneview_firmware_driver_config: "{{ role_path }}/files/oneview_config.json"
oneview_firmware_driver_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
