---
# defaults file for oneview_san_manager
oneview_san_manager_config: "{{ role_path }}/files/oneview_config.json"
oneview_san_manager_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
oneview_san_manager_config_file: "{{ lookup('file', oneview_san_manager_config) }}"
