---
# defaults file for oneview_storage_system_facts
oneview_storage_system_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_storage_system_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
