---
# defaults file for oneview_dynamic_role
oneview_dynamic_role_config: "{{ role_path }}/files/oneview_config.json"
oneview_dynamic_role_config_file: "{{ lookup('file', oneview_dynamic_role_config) }}"
oneview_dynamic_role_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
