---
# defaults file for oneview_certificates_server

oneview_certificates_server_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_certificates_server_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
