---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_hypervisor_manager_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_hypervisor_manager_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_hypervisor_manager_session

- name: Get currentVersion from URL
  oneview_version_facts:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
  delegate_to: localhost
  when: oneview_hypervisor_manager_config_file.api_version == ""
  register: oneview_hypervisor_manager_version

- name: Gather facts about a Server Certificate by remote address
  oneview_certificates_server_facts:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    remote: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
  delegate_to: localhost

- name: Run ansible.builtin.set_fact
  ansible.builtin.set_fact:
    oneview_hypervisor_manager_certificate: "{{ remote_certificate['certificateDetails'][0]['base64Data'] }}"

# Server Certificate need to be added to appliance for creating a hypervisor manager
- name: Create a Server Certificate
  oneview_certificates_server:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: present
    name: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
    data:
      certificateDetails:
        - aliasName: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
          base64Data: "{{ oneview_hypervisor_manager_certificate }}"
  delegate_to: localhost

- name: Create a Hypervisor Manager
  oneview_hypervisor_manager:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: present
    data:
      name: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
      displayName: vcenter
      hypervisorType: Vmware
      username: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_username }}"
      password: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_password }}"
  delegate_to: localhost
  register: oneview_hypervisor_manager_hyp_mgr_1

- name: Do nothing with the Hypervisor Manager when no changes are provided
  oneview_hypervisor_manager:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: present
    data:
      name: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
      displayName: vcenter
      hypervisorType: Vmware
  delegate_to: localhost

- name: Update the Hypervisor Manager changing the attribute displayName
  oneview_hypervisor_manager:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: present
    data:
      name: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
      displayName: vcenter renamed
      hypervisorType: Vmware
      username: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_username }}"
      password: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_password }}"
  delegate_to: localhost

- name: Delete the Hypervisor Manager
  oneview_hypervisor_manager:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: absent
    data: "{{ oneview_hypervisor_manager_hyp_mgr_1.ansible_facts.hypervisor_manager }}"
  delegate_to: localhost
  register: oneview_hypervisor_manager_deleted

- name: Do nothing when Hypervisor Manager is absent
  oneview_hypervisor_manager:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: absent
    data: "{{ oneview_hypervisor_manager_hyp_mgr_1.ansible_facts.hypervisor_manager }}"
  delegate_to: localhost
  register: oneview_hypervisor_manager_deleted

- name: Gather facts about a Server Certificate by remote address
  oneview_certificates_server_facts:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    remote: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
  delegate_to: localhost

- name: Run ansible.builtin.set_fact
  ansible.builtin.set_fact:
    oneview_hypervisor_manager_certificate: "{{ remote_certificate['certificateDetails'][0]['base64Data'] }}"

- name: Re-create a Server Certificate
  oneview_certificates_server:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: present
    name: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
    data:
      certificateDetails:
        - aliasName: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
          base64Data: "{{ oneview_hypervisor_manager_certificate }}"
  delegate_to: localhost

- name: Re-create a Hypervisor Manager to ensure continuity for automation script
  oneview_hypervisor_manager:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
    state: present
    data:
      name: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_name }}"
      displayName: vcenter
      hypervisorType: Vmware
      username: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_username }}"
      password: "{{ oneview_hypervisor_manager_contents.hypervisor_manager.hypervisor_manager_password }}"
  delegate_to: localhost

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_hypervisor_manager_config }}"
    sessionID: "{{ oneview_hypervisor_manager_session.ansible_facts.session }}"
  delegate_to: localhost
