---
# defaults file for oneview_logical_interconnect_facts
oneview_logical_interconnect_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_logical_interconnect_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
