---
# defaults file for oneview_server_hardware
oneview_server_hardware_config: "{{ role_path }}/files/oneview_config.json"
oneview_server_hardware_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
