---
# defaults file for oneview_fcoe_network_facts
oneview_fcoe_network_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
oneview_fcoe_network_facts_config: "{{ role_path }}/files/oneview_config.json"
