---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_server_hardware_type_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_server_hardware_type_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_server_hardware_type_facts_session

- name: Gather facts about all Server Hardware Types
  oneview_server_hardware_type_facts:
    config: "{{ oneview_server_hardware_type_facts_config }}"
    sessionID: "{{ oneview_server_hardware_type_facts_session.ansible_facts.session }}"
  delegate_to: localhost
- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: "{{ server_hardware_types | map(attribute='name') | list }}"

- name: Gather paginated, filtered and sorted facts about Server Hardware Types
  oneview_server_hardware_type_facts:
    config: "{{ oneview_server_hardware_type_facts_config }}"
    sessionID: "{{ oneview_server_hardware_type_facts_session.ansible_facts.session }}"
    params:
      start: 0
      count: 5
      sort: name:ascending
      filter: formFactor='HalfHeight'
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: "{{ server_hardware_types | map(attribute='name') | list }}"

- name: Gather facts about a Server Hardware Type by name
  oneview_server_hardware_type_facts:
    config: "{{ oneview_server_hardware_type_facts_config }}"
    sessionID: "{{ oneview_server_hardware_type_facts_session.ansible_facts.session }}"
    name: SY 480 Gen9 1
  delegate_to: localhost
- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: server_hardware_types

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_server_hardware_type_facts_config }}"
    sessionID: "{{ oneview_server_hardware_type_facts_session.ansible_facts.session }}"
  delegate_to: localhost
