---
# defaults file for oneview_connection_template_facts
oneview_connection_template_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_connection_template_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
