---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_certificates_server_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_certificates_server_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_certificates_server_session

- name: Get currentVersion from URL
  oneview_version_facts:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
  delegate_to: localhost
  when: oneview_certificates_server_config_file.api_version == ""
  register: oneview_certificates_server_version

- name: Gather facts about a Server Certificate by remote address
  oneview_certificates_server_facts:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
    remote: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
  delegate_to: localhost

- name: Run ansible.builtin.set_fact
  ansible.builtin.set_fact:
    oneview_certificates_server_certificate: "{{ remote_certificate['certificateDetails'][0]['base64Data'] }}"

- name: Create a Server Certificate
  oneview_certificates_server:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
    state: present
    name: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
    data:
      certificateDetails:
        - aliasName: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
          base64Data: "{{ oneview_certificates_server_certificate }}"
  delegate_to: localhost
  register: oneview_certificates_server_svr_cert

- name: Do nothing with the Server Certificate when no changes are provided
  oneview_certificates_server:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
    state: present
    name: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
    data:
      category: certificates
  delegate_to: localhost

- name: Update the Server Certificate changing the attribute name
  oneview_certificates_server:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
    state: present
    name: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
    data:
      name: test
      certificateDetails:
        - aliasName: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
          base64Data: "{{ oneview_certificates_server_certificate }}"
  delegate_to: localhost

- name: Delete the Server Certificate
  oneview_certificates_server:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
    state: absent
    name: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
    data: "{{ oneview_certificates_server_svr_cert.ansible_facts.certificate_server }}"
  delegate_to: localhost
  register: oneview_certificates_server_deleted

- name: Do nothing when Server Certificate is absent
  oneview_certificates_server:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
    state: absent
    name: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
    data: "{{ oneview_certificates_server_svr_cert.ansible_facts.certificate_server }}"
  delegate_to: localhost
  register: oneview_certificates_server_deleted

- name: Re-create a Server Certificate to support automation
  oneview_certificates_server:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
    state: present
    name: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
    data:
      certificateDetails:
        - aliasName: "{{ oneview_certificates_server_contents.certificates_server.remote_server }}"
          base64Data: "{{ oneview_certificates_server_certificate }}"
  delegate_to: localhost
  register: oneview_certificates_server_svr_cert

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_certificates_server_config }}"
    sessionID: "{{ oneview_certificates_server_session.ansible_facts.session }}"
  delegate_to: localhost
