---
# defaults file for oneview_volume
oneview_volume_config: "{{ role_path }}/files/oneview_config.json"
oneview_volume_config_file: "{{ lookup('file', oneview_volume_config) }}"
oneview_volume_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
