---
# defaults file for oneview_fc_network
oneview_fc_network_config: "{{ role_path }}/files/oneview_config.json"
oneview_fc_network_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
oneview_fc_network_config_file: "{{ lookup('file', oneview_fc_network_config) }}"
