---
# defaults file for oneview_server_profile
oneview_server_profile_config: "{{ role_path }}/files/oneview_config.json"
oneview_server_profile_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
