---
# defaults file for oneview_logical_enclosure
oneview_logical_enclosure_config: "{{ role_path }}/files/oneview_config.json"
oneview_logical_enclosure_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
