---
# ---
# defaults file for oneview_enclosure
oneview_enclosure_config: "{{ role_path }}/files/oneview_config.json"
oneview_enclosure_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
