---
# defaults file for oneview_volume_facts
oneview_volume_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_volume_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
