---
# ---
# defaults file for oneview_drive_enclosure
oneview_drive_enclosure_config: "{{ role_path }}/files/oneview_config.json"
oneview_drive_enclosure_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
