---
# defaults file for oneview_hypervisor_cluster_profile
oneview_hypervisor_cluster_profile_config: "{{ role_path }}/files/oneview_config.json"
oneview_hypervisor_cluster_profile_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
