---
# defaults file for oneview_fcoe_network
oneview_fcoe_network_config: "{{ role_path }}/files/oneview_config.json"
oneview_fcoe_network_config_file: "{{ lookup('file', oneview_fcoe_network_config) }}"
oneview_fcoe_network_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
