---
# defaults file for oneview_ethernet_network
oneview_ethernet_network_config: "{{ role_path }}/files/oneview_config.json"
oneview_ethernet_network_config_file: "{{ lookup('file', oneview_ethernet_network_config) }}"
oneview_ethernet_network_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
