---
# defaults file for oneview_appliance_time_and_locale_configuration
oneview_appliance_time_and_locale_configuration_config: "{{ role_path }}/files/oneview_config.json"
oneview_appliance_time_and_locale_configuration_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
