---
# defaults file for oneview_sas_interconnect_type_facts
oneview_sas_interconnect_type_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_sas_interconnect_type_facts_config_file: "{{ lookup('file', oneview_sas_interconnect_type_facts_config) }}"
oneview_sas_interconnect_type_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
