---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_id_pools_ipv4_range_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_id_pools_ipv4_range_facts_session

- name: Get facts about the IPv4 Subnet
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    sessionID: "{{ oneview_id_pools_ipv4_range_facts_session.ansible_facts.session }}"
    networkId: "{{ oneview_id_pools_ipv4_range_facts_contents.id_pools_ipv4_range.networkId }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_subnets

- name: Run ansible.builtin.set_fact
  ansible.builtin.set_fact:
    oneview_id_pools_ipv4_range_facts_subnet_uri: "{{ id_pools_ipv4_subnets[0]['uri'] }}"
  when: id_pools_ipv4_subnets| length != 0

- name: Get ID Pools IPv4 Range Schema
  oneview_id_pools_ipv4_range_facts:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    sessionID: "{{ oneview_id_pools_ipv4_range_facts_session.ansible_facts.session }}"
    options:
      - schema
  delegate_to: localhost

- name: Get facts about all the ranges
  oneview_id_pools_ipv4_range_facts:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_ranges

- name: Get facts about all the ranges in in the '{{ oneview_id_pools_ipv4_range_facts_contents.id_pools_ipv4_range.subnet_name }}'
  oneview_id_pools_ipv4_range_facts:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    sessionID: "{{ oneview_id_pools_ipv4_range_facts_session.ansible_facts.session }}"
    subnetUri: "{{ oneview_id_pools_ipv4_range_facts_subnet_uri }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_ranges

- name: Get facts about the IPv4 range '{{ oneview_id_pools_ipv4_range_facts_contents.id_pools_ipv4_range.range_name }}'
  oneview_id_pools_ipv4_range_facts:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    sessionID: "{{ oneview_id_pools_ipv4_range_facts_session.ansible_facts.session }}"
    name: "{{ oneview_id_pools_ipv4_range_facts_contents.id_pools_ipv4_range.range_name }}"
    subnetUri: "{{ oneview_id_pools_ipv4_range_facts_subnet_uri }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_ranges

- name: Run ansible.builtin.set_fact
  ansible.builtin.set_fact:
    oneview_id_pools_ipv4_range_facts_range_uri: "{{ id_pools_ipv4_ranges[0]['uri'] }}"

- name: Get facts about the range '{{ oneview_id_pools_ipv4_range_facts_range_uri }}'
  oneview_id_pools_ipv4_range_facts:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    sessionID: "{{ oneview_id_pools_ipv4_range_facts_session.ansible_facts.session }}"
    uri: "{{ oneview_id_pools_ipv4_range_facts_range_uri }}"
  delegate_to: localhost
  when: oneview_id_pools_ipv4_range_facts_range_uri is defined

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_ranges

- name: Get facts about the range free and allocated fragments '{{ oneview_id_pools_ipv4_range_facts_range_uri }}'
  oneview_id_pools_ipv4_range_facts:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    sessionID: "{{ oneview_id_pools_ipv4_range_facts_session.ansible_facts.session }}"
    options:
      - freeFragments
      - allocatedFragments
    uri: "{{ oneview_id_pools_ipv4_range_facts_range_uri }}"
  delegate_to: localhost
  when: oneview_id_pools_ipv4_range_facts_range_uri is defined

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_ranges
- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_ranges_free_fragments
- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: id_pools_ipv4_ranges_allocated_fragments

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_id_pools_ipv4_range_facts_config }}"
    sessionID: "{{ oneview_id_pools_ipv4_range_facts_session.ansible_facts.session }}"
  delegate_to: localhost
