---
# defaults file for oneview_repositories
oneview_repositories_config: "{{ role_path }}/files/oneview_config.json"
oneview_repositories_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
