---
# defaults file for oneview_enclosure_group_facts
oneview_enclosure_group_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_enclosure_group_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
