---
# defaults file for oneview_storage_volume_attachment
oneview_storage_volume_attachment_config: "{{ role_path }}/files/oneview_config.json"
oneview_storage_volume_attachment_contents: "{{ lookup('file', oneview_storage_volume_attachment_config) }}"
oneview_storage_volume_attachment_server_profile_name: sp1
