---
# defaults file for oneview_id_pools_ipv4_subnets
oneview_id_pools_ipv4_subnet_config: "{{ role_path }}/files/oneview_config.json"
oneview_id_pools_ipv4_subnet_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
