---
# defaults file for oneview_hypervisor_manager_facts
oneview_hypervisor_manager_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_hypervisor_manager_facts_hypervisor_manager_name: <hypervisor_ip>
