---
# defaults file for oneview_scope
oneview_scope_config: "{{ role_path }}/files/oneview_config.json"
oneview_scope_config_file: "{{ lookup('file', oneview_scope_config) }}"
oneview_scope_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
