---
# defaults file for oneview_storage_pool
oneview_storage_pool_config: "{{ role_path }}/files/oneview_config.json"
oneview_storage_pool_config_file: "{{ lookup('file', oneview_storage_pool_config) }}"
oneview_storage_pool_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
