---
# defaults file for oneview_firmware_driver_facts
oneview_firmware_driver_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_firmware_driver_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
