---
# defaults file for oneview_appliance_network_interface_facts
oneview_appliance_network_interface_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_appliance_network_interface_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
