---
# defaults file for oneview_certificates_server

oneview_certificates_server_config: "{{ role_path }}/files/oneview_config.json"
oneview_certificates_server_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
oneview_certificates_server_config_file: "{{ lookup('file', oneview_certificates_server_config) }}"
