---
# defaults file for oneview_storage_volume_attachment_facts
oneview_storage_volume_attachment_facts_config: "{{ role_path }}/files/oneview_config.json"
oneview_storage_volume_attachment_facts_config_file: "{{ lookup('file', oneview_storage_volume_attachment_facts_config) }}"
oneview_storage_volume_attachment_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
