#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------

ANSIBLE_METADATA = {'metadata_version': '1.1',
                    'status': ['preview'],
                    'supported_by': 'community'}

DOCUMENTATION = '''
---
module: oneview_version_facts
short_description: Returns the range of possible API versions supported by the appliance
description:
    - Provides an interface to return the range of possible API versions supported by the appliance.
version_added: "2.5"
requirements:
    - "hpeOneView >= 4.3.0"
author: "Priyanka Sood (@soodpr)"
validate_etag:
        description:
            - When the ETag Validation is enabled, the request will be conditionally processed only if the current ETag
                for the resource matches the ETag provided in the data.
        default: true
        choices: []
        type: bool
    api_version:
        description:
            - List with the api_version.
        required: false
        type: int
    hostname:
        description:
            - List with the hostname.
        required: false
        type: str
    image_streamer_hostname:
        description:
            - List with the image_streamer_hostname.
        required: false
        type: str
    password:
        description:
            - List with the password.
        required: false
        type: str
    auth_login_domain:
        description:
            - List with the auth_login_domain.
        required: false
        type: str
    username:
        description:
            - List with the username.
        required: false
        type: str
    config:
      description:
        - Path to a .json configuration file containing the OneView client configuration.
          The configuration file is optional. If the file path is not provided, the configuration will be loaded from
          environment variables.
      required: false
      type: path
notes:
    - "A sample configuration file for the config parameter can be found at:
       U(https://github.com/HewlettPackard/oneview-ansible/blob/master/examples/oneview_config-rename.json)"
    - "Check how to use environment variables for configuration at:
       U(https://github.com/HewlettPackard/oneview-ansible#environment-variables)"
    - "Additional Playbooks for the HPE OneView Ansible modules can be found at:
       U(https://github.com/HewlettPackard/oneview-ansible/tree/master/examples)"
    '''

EXAMPLES = '''
- name: Gather facts about current and minimum Version
  oneview_version_facts:
    config: "{{ config_file_path }}"

- debug: var=version
'''

RETURN = '''
version:
    description: Has the facts about the OneView current and minimum version.
    returned: When requested, but can not be null
    type: dict
'''

from ansible.module_utils.oneview import OneViewModuleBase


class VersionFactsModule(OneViewModuleBase):
    def __init__(self):
        super().__init__(additional_arg_spec=dict())

    def execute_module(self):
        version = self.oneview_client.versions.get_version()
        return dict(changed=False,
                    ansible_facts=dict(version=version))


def main():
    VersionFactsModule().run()


if __name__ == '__main__':
    main()