---
# defaults file for oneview_appliance_proxy_configuration
oneview_appliance_proxy_configuration_config: "{{ role_path }}/files/oneview_config.json"
oneview_appliance_proxy_configuration_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
