---
# defaults file for oneview_scope_facts
oneview_scope_facts_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
oneview_scope_facts_config: "{{ role_path }}/files/oneview_config.json"
