---
# defaults file for oneview_logical_interconnect_group
oneview_logical_interconnect_group_config: "{{ role_path }}/files/oneview_config.json"
oneview_logical_interconnect_group_config_file: "{{ lookup('file', oneview_logical_interconnect_group_config) }}"
oneview_logical_interconnect_group_contents: "{{ lookup('file', '../config/config.json') | from_json }}"
