---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ oneview_fcoe_network_facts_config }}"
    name: Test_Session
  delegate_to: localhost
  register: oneview_fcoe_network_facts_session

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: oneview_fcoe_network_facts_session

- name: Gather facts about all FCoE Networks
  oneview_fcoe_network_facts:
    config: "{{ oneview_fcoe_network_facts_config }}"
    sessionID: "{{ oneview_fcoe_network_facts_session.ansible_facts.session }}"
  delegate_to: localhost

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: fcoe_networks

- name: Gather paginated, filtered and sorted facts about FCoE Networks
  oneview_fcoe_network_facts:
    config: "{{ oneview_fcoe_network_facts_config }}"
    sessionID: "{{ oneview_fcoe_network_facts_session.ansible_facts.session }}"
    params:
      start: 0
      count: 3
      sort: name:descending
      filter: vlanId=2

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: fcoe_networks

- name: Gather facts about a FCoE Network by name
  oneview_fcoe_network_facts:
    config: "{{ oneview_fcoe_network_facts_config }}"
    sessionID: "{{ oneview_fcoe_network_facts_session.ansible_facts.session }}"
    name: "{{ fcoe_networks[0]['name'] }}"
  delegate_to: localhost
  when: fcoe_networks | default('', True)

- name: Run ansible.builtin.debug
  ansible.builtin.debug:
    var: fcoe_networks

- name: Logout Session
  oneview_logout_session:
    config: "{{ oneview_fcoe_network_facts_config }}"
    sessionID: "{{ oneview_fcoe_network_facts_session.ansible_facts.session }}"
  delegate_to: localhost
